fix: fix the vulnerability of github action
freeCodeCamp/chinese pull request #1244
Opened 2024-05-18 16:44 UTC by stevending1st

Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #XXXXX

2024-05-19 13:55 UTC, TechQuery requested changes

2024-05-19 13:55 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +        if: ${{ env.issue_body && startsWith(env.issue_title, '[Auto]') }}
直接用给 GitHub 内置变量是没问题的，他让你用环境变量是指在 shell 脚本里面。

2024-05-19 13:55 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +        run: echo "This issue does not need to generate a markdown file." 1>&2; exit 1;
```suggestion
        run: echo "This issue does not need to generate a markdown file." 1>&2; exit 1;
```
这么简单的语句，所有 shell 都支持。

2024-05-19 13:55 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +        run: echo "The description of the issue is empty." 1>&2; exit 1;
把这些 step 还是放在你原来的顶部位置，这样后面就不需要做判断了。

2024-05-20 02:56 UTC, stevending1st commented on .github/workflows/WebPageToMarkdown.yml
> +        run: echo "The description of the issue is empty." 1>&2; exit 1;
> 把这些 step 还是放在你原来的顶部位置，这样后面就不需要做判断了。

检查可以置顶，但是后面要做判断，这样后续鲁棒性会高一点。

2024-05-20 02:57 UTC, stevending1st commented on .github/workflows/WebPageToMarkdown.yml
> +        run: echo "This issue does not need to generate a markdown file." 1>&2; exit 1;
> 这么简单的语句，所有 shell 都支持。

`1 > &2` 不兼容

2024-05-20 02:58 UTC, stevending1st commented on .github/workflows/WebPageToMarkdown.yml
> +        if: ${{ env.issue_body && startsWith(env.issue_title, '[Auto]') }}
> 直接用给 GitHub 内置变量是没问题的，他让你用环境变量是指在 shell 脚本里面。

理论上是这样，但是写起来会简单一些。

2024-05-20 06:36 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +        run: echo "The description of the issue is empty." 1>&2; exit 1;
> 检查可以置顶，但是后面要做判断，这样后续鲁棒性会高一点。

本来 step 就是前一步出错中断，后面就不会再进行了，遵循的是 Shell 脚本的设计。

如果判断条件变得越来越复杂，后面你每一步都要写同样的判断条件，那不就太麻烦了。

2024-05-20 06:39 UTC, TechQuery requested changes

2024-05-20 06:39 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +        if: ${{ env.issue_body && startsWith(env.issue_title, '[Auto]') }}
```suggestion
        if: ${{ startsWith(env.issue_title, '[Auto]') }}
```
issue 内容不存在前面就直接退出了，不需要在后面判断了。

2024-05-20 06:40 UTC, TechQuery commented on .github/workflows/WebPageToMarkdown.yml
> +        if: ${{ env.issue_body && startsWith(env.issue_title, '[Auto]') }}
> 理论上是这样，但是写起来会简单一些。

其实每一个变量只需要引用、判断一次，定义环境变量也占地方呀。

2024-05-20 15:22 UTC, merged

2024-05-22 08:53 UTC, miyaliu666 commented
谢谢 @stevending1st @TechQuery  我前天已经在 [security advisory](https://github.com/freeCodeCamp/chinese/security/advisories/GHSA-mf7p-4px7-wgjv) 中把你们添加为 remediation_developer 和 remediation_reviewer，现在等 reporter 查看和确认 PR，然后我会发布这个 advisory。

2024-05-22 10:29 UTC, miyaliu666 commented
好了，现在发布了，我把 reporter 也加上了。

另外，reporter 反馈 `${{ github.event.issue.Body }}` 中的 `Body` 开头字母应该是小写。

2024-05-22 13:37 UTC, TechQuery commented
> 另外，reporter 反馈 `${{ github.event.issue.Body }}` 中的 `Body` 开头字母应该是小写。

代码能运行、无报错，他也可以提 PR。